image: node:20

definitions:
  steps:
    - step: &install-and-build
        name: Install dependencies and run tests
        image: node:20
        script:
          - npm install
          - npm install -g @vue/cli
          - npm run build

    - step: &snyk-sec-test
        name: Install dependencies and run Snyk test
        image: snyk/snyk:python
        script:
          - snyk auth $SNYK_TOKEN
          - snyk test --severity-threshold=low --org=erselekmen27 || true

    - step: &build-and-deploy
        name: Build and Deploy to AWS Elastic Beanstalk
        deployment: training-app-env
        script:
          - npm install -g @vue/cli
          - npm run build
          - npm install -g awsebcli
          - eb init training-app --platform "Node.js 20" --region eu-central-1
          - eb setenv NODE_ENV=production
          - eb use training-app-env
          - eb deploy --staged --timeout 15

pipelines:
  default:
    - step: *install-and-build
    - step: *build-and-deploy
    - step: *snyk-sec-test
