image: node:20

definitions:
  steps:
    - step: &install-and-build
        name: Install npm dependencies and build the app
        caches:
          - node
        script:
          - npm install
          - npm install -g @vue/cli
          - npm run build
        artifacts:
          - dist/** # Replace with the path to your build directory

    - step: &deploy-to-s3
        name: Build and Deploy to AWS S3
        oidc: true
        script:
          - apt-get update
          - apt-get install -y awscli --upgrade
          - export AWS_REGION=eu-central-1
          - export AWS_ROLE_ARN=arn:aws:iam::110975517810:role/s3-bitbucket-access-role
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - aws s3 sync dist/ s3://training-app-data/


pipelines:
  branches:
    ersel-dev:
      - step: *install-and-build
      - step: *deploy-to-s3



#definitions:
#  steps:
#    - step: &sonarqube-quality-test
#        name: SonarQube Analysis
#        image: sonarsource/sonar-scanner-cli:latest
#        script:
#          - sonar-scanner -Dsonar.projectKey=$SQ_PROJECT_KEY -Dsonar.host.url=$SQ_EC2_HOST:$SQ_EC2_PORT -Dsonar.login=$SQ_TOKEN

#    - step: &snyk-sec-test
#        name: Install dependencies and run Snyk test
#        image: snyk/snyk:node
#        script:
#          - snyk auth $SNYK_TOKEN
#          - snyk test --severity-threshold=low --org=erselekmen27 || true

#    - step: &build-and-deploy
#        name: Build and Deploy to AWS Elastic Beanstalk
#        deployment: $EBS_ENV_NAME
#         script:
#          - npm install -g @vue/cli
#          - npm run build
#          - npm install -g awsebcli
#          - eb init $EBS_APP_NAME --platform "Node.js 20" --region $EBS_AWS_REGION
#          - eb setenv NODE_ENV=production
#          - eb use $EBS_ENV_NAME
#          - eb deploy --staged --timeout 15

#pipelines:
#  branches:
#    ersel-dev:
#    - step: *sonarqube-quality-test
#    - step: *snyk-sec-test
#    - step: *build-and-deploy