image: node:20

definitions:
  steps:
    - step: &snyk-sec-test
        name: Run Security Test with Snyk Code Security
        image: snyk/snyk:node
        script:
          - snyk auth $SNYK_TOKEN
          - snyk test --severity-threshold=low --org=erselekmen27 || true

#    - step: &sonarqube-quality-test
#        name: SonarQube Code Quality Analysis
#        image: sonarsource/sonar-scanner-cli:latest
#        script:
#          - sonar-scanner -Dsonar.projectKey=$SQ_PROJECT_KEY -Dsonar.host.url=$SQ_EC2_HOST:$SQ_EC2_PORT -Dsonar.login=$SQ_TOKEN

    - step: &install-and-build
        name: Install Dependencies and Build
        caches:
          - node
        script:
          - npm install
          - npm install -g @vue/cli
          - npm run build
        artifacts:
          - dist/**

    - step: &deploy-to-s3
        name: Install aws-cli and Deploy to AWS S3
        oidc: true
        script:
          - apt-get update
          - apt-get install -y awscli --upgrade
          - export AWS_REGION=$AWS_REGION
          - export AWS_ROLE_ARN=$AWS_ROLE_ARN
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - aws s3 sync dist/ s3://training-app-build/

    - step: &build-and-deploy-ecs
        name: Build and Deploy to ECS
        image: atlassian/pipelines-awscli  # Ensure this image has the necessary tools
        services:
          - docker
        script:
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            oidc: true
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_REGION
              IMAGE_NAME: $AWS_ECR_REPOSITORY
              AWS_OIDC_ROLE_ARN: $AWS_ROLE_ARN # Optional

          - pipe: atlassian/aws-ecs-deploy:1.12.1
            oidc: true
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_REGION
              AWS_OIDC_ROLE_ARN: $AWS_ROLE_ARN # Optional
              CLUSTER_NAME: $ECS_CLUSTER_NAME
              SERVICE_NAME: $ECS_SERVICE_NAME



pipelines:
  branches:
    ersel-dev:
      - step: *build-and-deploy-ecs
      - step: *snyk-sec-test
#      - step: *sonarqube-quality-test
      - step: *install-and-build
      - step: *deploy-to-s3
