image: node:20

definitions:
  steps:
    - step: &snyk-sec-test
        name: Run Security Test with Snyk Code Security
        image: snyk/snyk:node
        script:
          - snyk auth $SNYK_TOKEN
          - snyk test --severity-threshold=low --org=erselekmen27 || true

    - step: &sonarqube-quality-test
        name: SonarQube Code Quality Analysis
        clone:
          depth: full
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SQ_HOST_URL}
              SONAR_TOKEN: ${SQ_TOKEN}

    - step: &npm-build
        name: Install Dependencies and Build
        caches:
          - node
        script:
          - npm install
          - npm install -g @vue/cli
          - npm run build
        artifacts:
          - dist/**

    - step: &deploy-build-to-s3
        name: Install aws-cli and Deploy to AWS S3
        oidc: true
        script:
          - apt-get update
          - apt-get install -y awscli --upgrade
          - export AWS_REGION=$AWS_REGION
          - export AWS_ROLE_ARN=$AWS_ROLE_ARN
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - aws s3 sync dist/ s3://training-app-build/ --region eu-central-1

    - step: &build-image-to-ecr
        name: Build Docker Image and Push to ECR
        image: atlassian/pipelines-awscli
        services:
          - docker
        script:
          - docker build -t $AWS_ECR_REPOSITORY:latest -t $BITBUCKET_COMMIT .
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_REGION
              IMAGE_NAME: $AWS_ECR_REPOSITORY
              TAG: 'latest, $BITBUCKET_COMMIT'

    - step: &deploy-image-to-ecs
        name: Deploy to ECS
        image: atlassian/pipelines-awscli
        script:
          - pipe: atlassian/aws-ecs-deploy:1.12.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_REGION
              CLUSTER_NAME: $ECS_CLUSTER_NAME
              SERVICE_NAME: $ECS_SERVICE_NAME

  caches:
    sonar: ~/.sonar

clone:
  depth: full


pipelines:
  default:
    - step: *snyk-sec-test
    - step: *sonarqube-quality-test

  branches:
    dev:
      - step: *snyk-sec-test
      - step: *sonarqube-quality-test
      - step: *npm-build
      - step: *deploy-build-to-s3

    training-app_v2:
#      - step: *snyk-sec-test
#      - step: *sonarqube-quality-test
      - step: *build-image-to-ecr
      - step: *deploy-image-to-ecs


