image: node:20

definitions:
  steps:
    - step: &snyk-sec-test
        name: Run Security Test with Snyk Code Security
        image: snyk/snyk:node
        script:
          - snyk auth $SNYK_TOKEN
          - snyk test --severity-threshold=low --org=erselekmen27 || true

    - step: &install-and-build
        name: Install Dependencies and Build
        caches:
          - node
        script:
          - npm install
          - npm install -g @vue/cli
          - npm run build
        artifacts:
          - dist/**


    - pipe: atlassian/aws-s3-deploy:1.6.0
      variables:
        AWS_DEFAULT_REGION: $AWS_REGION # Optional if already defined in the context or OIDC used.
        AWS_OIDC_ROLE_ARN: $BITBUCKET_STEP_OIDC_TOKEN # Optional by default. Required for OpenID Connect (OIDC) authentication.
        AWS_ROLE_ARN: $AWS_ROLE_ARN # Optional. Required for STS authentication.
        S3_BUCKET: 'training-app-build'
        LOCAL_PATH: '$(pwd)'

pipelines:
  branches:
    dev:
      - step: *snyk-sec-test
      - step: *install-and-build
#     - step: *build-image
#     - step: *deploy-to-ecs

#definitions:
#  steps:
#    - step: &sonarqube-quality-test
#        name: SonarQube Analysis
#        image: sonarsource/sonar-scanner-cli:latest
#        script:
#          - sonar-scanner -Dsonar.projectKey=$SQ_PROJECT_KEY -Dsonar.host.url=$SQ_EC2_HOST:$SQ_EC2_PORT -Dsonar.login=$SQ_TOKEN


#pipelines:
#  branches:
#    ersel-dev:
#    - step: *sonarqube-quality-test