branch-defaults:
  main:
    environment: training-app-env
    group_suffix: null
global:
  application_name: training-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
