version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@1.3.0
  node: circleci/node@4.7.0
  # sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  snyk-security-test:
    docker:
      - image: snyk/snyk:node
    steps:
      - checkout
      - run:
          name: Run Security Test with Snyk Code Security
          command: |
            snyk auth $SNYK_TOKEN
            snyk test --severity-threshold=low --org=erselekmen27 || true

  # sonarqube-quality-test:
    # docker:
      # - image: circleci/sonarqube:latest
    # steps:
      # - checkout
      # - sonarcloud/scan

  npm-build:
    docker:
      - image: cimg/node:20.0  # Replace with the version of Node.js you are using
    steps:
      - checkout
      - restore_cache:  # restores saved cache if no changes in package.json
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Vue CLI Globally
          command: npm install -g @vue/cli
      - run:
          name: Build the Project
          command: npm run build
      - run:
          name: Update Title in index.html
          command: sed -i 's/<title>.*<\/title>/<title>Training App | S3<\/title>/' dist/index.html
      - save_cache:  # save cache for faster future builds
          key: node-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .  # This is the directory where all the job's steps are run
          paths:
            - dist  # This is the directory you want to persist

  deploy-build-to-s3:
    docker:
      - image: circleci/aws-cli@2.0.3
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Build to AWS S3
          command: |
            aws s3 sync dist/ $AWS_S3_BUCKET --region $AWS_REGION

  build-image-to-ecr:
    docker:
      - image: circleci/aws-cli@2.0.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_REGION)
            docker build -t $AWS_ECR_REPOSITORY:latest -t $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 .
            docker push $AWS_ECR_REPOSITORY:latest
            docker push $AWS_ECR_REPOSITORY:$CIRCLE_SHA1

  deploy-image-to-ecs:
    docker:
      - image: circleci/aws-cli@2.0.3
    steps:
      - checkout
      - run:
          name: Update ECS Service
          command: |
            aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --task-definition $TASK_DEFINITION

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - snyk-security-test
      # - sonarqube-quality-test
      - npm-build:
          filters:
            branches:
              only: [ersel-dev, dev, master]
      - build-image-to-ecr:
          filters:
            branches:
              only: [ersel-dev, dev, master]
      - deploy-build-to-s3:
          requires:
            - npm-build
          filters:
            branches:
              only: [ersel-dev, dev, master]
      - deploy-image-to-ecs:
          requires:
            - build-image-to-ecr
          filters:
            branches:
              only: [ersel-dev, dev, master]

